"""Generate the bundled synthetic `_data/` test fixture from a real ingest.

Derives a tiny, content-scrubbed dataset from a real `_data/` tree so the golden-parity
suite has something to render in CI without committing real captures (ADR-8). NOT run in
CI — run by hand to (re)generate the fixture, then commit the result + refreshed golden.

Scrubbing policy (ADR-8 + ADR-6):
  * area name           -> generic ("District 01")
  * marker/pass paths   -> KEYWORD-PRESERVING (keeps the draw_class keyword so the classifier
                           still produces the same class distribution; strips game content)
  * labels / names / file paths -> generic per-row tokens
  * counter names, formats, enums, blend/depth numerics -> KEPT (not content; load-bearing,
    e.g. 'GPU Duration' drives pass_gpu)
  * row counts truncated to --rows per table

Usage (from the venv):
  python -m bobframes.tests.make_synthetic \
      --src "c:/Users/vsiva/Downloads/RDC mainline r110565 25-05-2026/_data" \
      --out bobframes/tests/data/synthetic --rows 60
"""
from __future__ import annotations

import argparse
import json
import os

import pyarrow as pa
import pyarrow.parquet as pq

from .. import paths as _paths
from .. import schemas

SYNTH_AREA = "District 01"
FIXED_TS = "2026-01-01T00:00:00+00:00"

# Two synthetic drops (different build labels/dates) so trend/sparkline reports have >1 point.
DROPS = [
    {"date": "2026-05-27", "label": "r110565"},
    {"date": "2026-05-28", "label": "r110600"},
]

# Derived tables are regenerated by render-only (derive/pass_class_breakdown/texture_usage); skip.
SKIP_TABLES = {"pass_class_breakdown", "texture_usage"}

# String columns that carry game content -> generic per-row token.
GENERIC_SCRUB = {
    "draw_name", "label", "src_file_path", "declared_label",
    "attribute_name", "usage_name",
}
# Marker/pass-path columns -> keyword-preserving (keeps draw_class coverage).
MARKER_SCRUB = {
    "marker_path", "marker_path_norm", "parent_pass_path", "parent_pass_path_norm",
    "parent_marker_path",
}
_STRING_TYPES = (pa.string(), pa.large_string())


def _marker_token(mp: str) -> str:
    """Return a class-preserving stand-in for a marker path (mirrors _classify_draw order)."""
    s = (mp or "").lower()
    if "shadow" in s:
        return "shadow"
    if "prepass" in s or "depthonly" in s:
        return "prepass"
    if "slate" in s or "/ui" in s or s.endswith("ui"):
        return "slate"          # -> ui branch
    if "postprocess" in s or "tonemap" in s or "bloom" in s or "eyeadapt" in s:
        return "postprocess"
    if "decal" in s:
        return "decal"
    if "translucen" in s:
        return "translucent"
    if "basepass" in s:
        return "basepass"
    return "scene"              # no keyword -> class falls to blend/depth (preserved)


def _scrub_table(t: pa.Table, area: str, date: str, label: str) -> pa.Table:
    n = t.num_rows
    field_type = {f.name: f.type for f in t.schema}
    out = {}
    for name in t.column_names:
        ft = field_type[name]
        if name == "area":
            out[name] = pa.array([area] * n, type=ft)
        elif name == "drop_date":
            out[name] = pa.array([date] * n, type=ft)
        elif name == "drop_label":
            out[name] = pa.array([label] * n, type=ft)
        elif name in MARKER_SCRUB and ft in _STRING_TYPES:
            orig = t.column(name).to_pylist()
            out[name] = pa.array(
                [f"Frame 1/{_marker_token(v)}/p{i}" if v is not None else None
                 for i, v in enumerate(orig)],
                type=ft,
            )
        elif name in GENERIC_SCRUB and ft in _STRING_TYPES:
            orig = t.column(name).to_pylist()
            out[name] = pa.array(
                [f"{name}_{i}" if v is not None else None for i, v in enumerate(orig)],
                type=ft,
            )
        else:
            out[name] = t.column(name)
    # Preserve column order exactly (schema regression checks names/order).
    return pa.table({name: out[name] for name in t.column_names})


def _build_drop(src_area_dir: str, src_drop: str, out_drop_dir: str,
                date: str, label: str) -> dict:
    os.makedirs(out_drop_dir, exist_ok=True)
    src_drop_dir = os.path.join(src_area_dir, src_drop)
    row_counts: dict[str, int] = {}
    captures: set[str] = set()
    for stem in schemas.TABLES:
        if stem in SKIP_TABLES:
            continue
        src = os.path.join(src_drop_dir, f"{stem}.parquet")
        if not os.path.exists(src):
            continue
        t = pq.read_table(src)
        t = t.slice(0, ARGS.rows)
        t = _scrub_table(t, SYNTH_AREA, date, label)
        pq.write_table(t, os.path.join(out_drop_dir, f"{stem}.parquet"), compression="snappy")
        row_counts[stem] = t.num_rows
        if "capture" in t.column_names:
            captures.update(str(c) for c in t.column("capture").to_pylist() if c is not None)
    caps = sorted(captures, key=lambda x: (len(x), x))
    manifest = {
        "schema_version": schemas.SCHEMA_VERSION,
        "build_timestamp": FIXED_TS,
        "area": SYNTH_AREA,
        "drop_date": date,
        "drop_label": label,
        "captures": caps,
        "capture_status": {c: "ok" for c in caps},
        "row_counts": row_counts,
        "rotated_from": None,
    }
    with open(os.path.join(out_drop_dir, _paths.MANIFEST_NAME), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    return {"label": label, "tables": len(row_counts), "captures": caps}


def main() -> int:
    src = ARGS.src
    areas = sorted(d for d in os.listdir(src) if os.path.isdir(os.path.join(src, d)))
    if len(areas) < len(DROPS):
        raise SystemExit(f"need >= {len(DROPS)} source areas, found {len(areas)} in {src}")
    out_area = os.path.join(ARGS.out, _paths.DATA_DIR, SYNTH_AREA)
    for spec, src_area in zip(DROPS, areas):
        src_area_dir = os.path.join(src, src_area)
        src_drops = sorted(d for d in os.listdir(src_area_dir)
                           if os.path.isdir(os.path.join(src_area_dir, d)))
        if not src_drops:
            raise SystemExit(f"no drops under {src_area_dir}")
        out_drop = os.path.join(out_area, f"{spec['date']}_{spec['label']}")
        info = _build_drop(src_area_dir, src_drops[0], out_drop, spec["date"], spec["label"])
        print(f"  {SYNTH_AREA}/{spec['date']}_{spec['label']}  <- {src_area}/{src_drops[0]}  "
              f"({info['tables']} tables, captures={info['captures']})")
    print(f"synthetic _data written under {os.path.join(ARGS.out, _paths.DATA_DIR)}")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(prog="bobframes.tests.make_synthetic")
    ap.add_argument("--src", required=True, help="real _data/ tree to derive from")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "data", "synthetic"))
    ap.add_argument("--rows", type=int, default=60, help="max rows per table")
    ARGS = ap.parse_args()
    raise SystemExit(main())
